testing manual ssh approval

diff --git a/rootfs/etc/s6-overlay/s6-rc.d/backup/run b/rootfs/etc/s6-overlay/s6-rc.d/backup/run
--- a/rootfs/etc/s6-overlay/s6-rc.d/backup/run
+++ b/rootfs/etc/s6-overlay/s6-rc.d/backup/run
@@ -6,10 +6,10 @@
 declare backup_enable
 declare host
 declare username
-declare password
 declare m_cloud_server_ip
 backup_enable=false
 bashio::log.info "---------Backup status---------"
+
 m_cloud_server_ip="10.170.204.1"
 # Get config input from addon UI
 if bashio::config.has_value "server.enable_backup"; then
@@ -31,9 +31,10 @@ fi
 if bashio::config.has_value "server.username"; then
     username=$(bashio::config "server.username")
 fi
-if bashio::config.has_value "server.password"; then
-    password=$(bashio::config "server.password")
-fi
+
+# Print the SSH public key
+pubkey=$(cat "/data/backup_cred/$username.pub")
+bashio::log.info "The ssh public key is: $pubkey"
 
 USERNAME="$username"
 FILE_DESTINATION="$USERNAME@$host:/m-connect/$USERNAME"
@@ -43,13 +44,12 @@ FILE_SOURCE="/home/$USERNAME.tar"
 CURRENT_TIMESTAMP=$(date +%s)  # get the current timestamp in seconds since Unix epoch
 TARGET_TIMESTAMP=$(( CURRENT_TIMESTAMP - 82800 ))  # subtract 23 hours from the current timestamp. To make sure the backup creation time is accounted for.
 
-
-# Check the file on the m-cloud server. If it's newer than the backup intervall exit the script and try again.
+# Check the file on the m-cloud server. If it's newer than the backup intervall exit the script and try again after the delay.
 # Turn off "exit on error" option
 set +e
-fileinfo=$(sshpass -p "$password" ssh $USERNAME@$m_cloud_server_ip "stat -c %y /m-connect/$USERNAME/$USERNAME.tar")
-# Turn off "exit on error" option
-set +e
+fileinfo=$(ssh $USERNAME@$m_cloud_server_ip "stat -c %y /m-connect/$USERNAME/$USERNAME.tar")
+# Turn on "exit on error" option
+set -e
 newdate=$(date -d "$fileinfo" +%s)
 
 if [ $? -ne 0 ]; then
@@ -64,7 +64,6 @@ else
 bashio::log.info "File on m-cloud server is not newer than backup creation target. A new one should be created."
 fi
 fi
-
 
 # Get the supervisor token from os environment
 SUPER_TOKEN=${SUPERVISOR_TOKEN}
@@ -125,7 +124,7 @@ fi
 # Turn off "exit on error" option
 set +e
 
-sshpass -p "$password" rsync $FILE_SOURCE $FILE_DESTINATION 2>&1 | tee /tmp/rsync.log
+rsync $FILE_SOURCE $FILE_DESTINATION 2>&1 | tee /tmp/rsync.log
 RSYNC_EXIT_STATUS=${PIPESTATUS[0]}
 # Turn "exit on error" option back on
 set -e
